annotate_root: splits/LKTL-37141
batch_size: 128
class_labels: LKTL_Long
data_cols:
- 88
- 125
data_root: C:/Carabid_Data/CV-eDNA
device: cuda
file_name: Label
hidden_size: 128
image_size:
- 224
- 224
learning_rate: 0.001
num_classes: 37
num_col: 37
num_epochs: 100
num_workers: 4
seed: 32678456782
short_labels: LKTL
weight_decay: 0.001
