# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

experiment_name: image-only

# environment/computational parameters
seed: 32678456782       # random number generator seed (long integer value)
device: cuda
num_workers: 4

# dataset parameters
data_root: C:/Carabid_Data/CV-eDNA
annotate_root: splits/LKTL-37141
class_labels: LKTL_Long
short_labels: LKTL
file_name: Label
num_classes: 37

# training hyperparameters
image_size: [224, 224]
num_epochs: 100
batch_size: 128
learning_rate: 0.001
weight_decay: 0.001